version: '3.8'

services:
  # MongoDB数据库
  mongodb:
    image: mongo:6.0
    container_name: ai-coach-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ai_programming_coach
    volumes:
      - mongodb_data:/data/db
    networks:
      - ai-coach-network

  # AI编程教练应用
  app:
    build: .
    container_name: ai-coach-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/ai_programming_coach
      - JWT_SECRET=ai_programming_coach_super_secret_jwt_key_2024
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BCRYPT_ROUNDS=12
    depends_on:
      - mongodb
    networks:
      - ai-coach-network
    volumes:
      - ./server/.env:/app/server/.env:ro

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: ai-coach-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - ai-coach-network

volumes:
  mongodb_data:

networks:
  ai-coach-network:
    driver: bridge

