# Railway Nixpacks配置
# 用于配置Python环境和依赖

[phases.setup]
nixPkgs = ["nodejs-18_x", "python39", "python39Packages.pip", "poppler_utils"]

[phases.install]
cmds = [
  "cd server && npm install --production",
  "python3 -m pip install --user pdf2image Pillow requests 'urllib3<2'"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "cd server && node index.js"

