# Railway Nixpacks配置
# 简化版本 - 仅 Node.js，暂时禁用 Python（PDF功能）

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd server && npm install --production"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd server && node index.js"

