# Render 部署配置文件
# 用于自动化部署后端服务

services:
  # 后端 Web 服务
  - type: web
    name: ai-news-hub-backend
    runtime: node
    region: oregon  # 或选择离你最近的区域
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    healthCheckPath: /api/health
    envVars:
      # Node 环境
      - key: NODE_ENV
        value: production
      
      # 阿里云百炼配置
      - key: ALIYUN_BAILIAN_API_KEY
        sync: false  # 手动在 Render 控制台设置
      - key: ALIYUN_BAILIAN_APP_ID
        sync: false
      - key: ALIYUN_BAILIAN_TEXT_MODEL
        value: qwen3-max
      - key: ALIYUN_BAILIAN_VISION_MODEL
        value: qwen-vl-max
      
      # 阿里云 OSS 配置
      - key: ALIYUN_OSS_ACCESS_KEY_ID
        sync: false
      - key: ALIYUN_OSS_ACCESS_KEY_SECRET
        sync: false
      - key: ALIYUN_OSS_REGION
        value: oss-cn-beijing
      - key: ALIYUN_OSS_BUCKET
        sync: false
      
      # 数据库配置（使用外部 MongoDB Atlas）
      - key: MONGODB_URI
        sync: false
      
      # JWT 配置
      - key: JWT_SECRET
        generateValue: true  # Render 自动生成
      - key: BCRYPT_ROUNDS
        value: 12
    
    # 自动部署设置
    autoDeploy: true
    
    # 构建过滤器（仅当 server 目录变化时重新部署）
    buildFilter:
      paths:
        - server/**
        - package.json
